AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
    twitterresponder:
        Type: 'AWS::Serverless::Function'
        Properties:
           Handler: lambda_function.lambda_handler
           Runtime: python3.7
           CodeUri: ./twitter-responder/
           MemorySize: 1024
           Timeout: 10
